name: pushdocker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04  
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
    - name: login docker
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        #启用 buildx 插件
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker buildx version
        docker run --privileged --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
        docker buildx create --use --name mybuilder
        docker buildx inspect mybuilder --bootstrap
        docker buildx ls
    - name: go buildx
      run: |
        #使用 buildx 构建 并推送倒hub
        docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/clash --platform linux/arm64,linux/amd64 . --push
